<?php
// $Host is the URL generated by llRequestURL() in world.
// $PostData is a string of information to send to the prim. Example: FARTAPI=fart=Christina.Vortex
// That would then tell the prim to fart on a resident by the name of Chrisx Vortex.
// PHP 5.3 or higher is suggested but any build that has explode(), count() and fsockopen() will do.
	function senddata($Host, $PostData) {
		$Port = 80;
		$Method = "POST";
		if (strtolower(substr($Host, 0, 5)) == "https") {
			$Port = 443;
		}
		$Host = explode("//", $Host, 2);
		if (count($Host) < 2) {
			$Host[1] = $Host[0];
		}
		$Host = explode("/", $Host[1], 2);
		if ($Port == 443) {
			$SSLAdd = "ssl://";
		}
		$Host[0] = explode(":", $Host[0]);
		if (count($Host[0]) > 1) {
			$Port = $Host[0][1];
			$Host[0] = $Host[0][0];
		}else{
			$Host[0] = $Host[0][0];
		}
		$Socket = @fsockopen($SSLAdd.$Host[0], $Port, $Dummy1, $Dummy2, 1); // this is needed to connect to another server.
		if ($Socket) {
  			fputs($Socket, "$Method /$Host[1] HTTP/1.1\r\n".
				 "Host: $Host[0]\r\n".
				 "Content-type: application/x-www-form-urlencoded\r\n".
				 "User-Agent: Opera/9.01 (Windows NT 5.1; U; en)\r\n".
				 "Accept-Language: de-DE,de;q=0.9,en;q=0.8\r\n".
				 "Accept-Charset: iso-8859-1, utf-8, utf-16, *;q=0.1\r\n".
				 "Content-length: ".strlen($PostData)."\r\n".
				 "Connection: close\r\n".
				 "\r\n".
				 $PostData);
  			$Tme = time();
  			while(!feof($Socket) && $Tme + 30 > time()) {
  				$Res = $Res.fgets($Socket, 256);
  			}
			fclose($Socket);
		}
		$Res = explode("\r\n\r\n", $Res, 2);
 		return $Res[1];
	}
// Dont really know what all that above does but it works.
// You can use this function anywhere in your php files. Below is a example of how to do it.

$primurl = ""; // this would be the address that llRequestURL() generated and said in local chat for you.
$data = "FARTAPI=fart=Christina.Vortex"; // This is data we want to send. Remember you can change any part of this.
// Your welcome to leave as is if testing it on ZetaWorlds, Next Reality or Great Canadian Grid since i have the same name on all of those grids.

// Now lets send that info to the script above and display the results in the browser
echo senddata($primurl, $data); // its that simple.

// now open this page in your browser and watch the magic in world.
// DISCLAIMER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This and the included lsl file is just a tutorial to help other opensim/sl users know how to send data to a prim from a website.
// You are very welcome to use and mod this and the included lsl all you want, just please dont redistrube this tutorial as your own.
// Credit where credit is due.
?>